import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:responsive_framework/responsive_framework.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';

import 'core/network/api_client.dart';
import 'core/theme/app_theme.dart';
import 'router/app_router.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

// ── FCM Background Handler ─────────────────────────────────
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // Background notification handling (silent push)
  debugPrint('[FCM] Background message: ${message.messageId}');
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── 1. Initialize Dio API Client ──────────────────────────
  ApiClient.instance.initialize();

  // ── 2. Initialize Firebase (FCM) ──────────────────────────
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  // ── 3. Request notification permissions ───────────────────
  final messaging = FirebaseMessaging.instance;
  await messaging.requestPermission(
    alert: true,
    badge: true,
    sound: true,
  );

  // ── 4. Launch App ─────────────────────────────────────────
  runApp(const ProviderScope(child: KatiyaStationApp()));
}

class KatiyaStationApp extends ConsumerWidget {
  const KatiyaStationApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(appRouterProvider);
    return MaterialApp.router(
      title: 'Katiya Station RMS',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.darkTheme,
      routerConfig: router,
      builder: (context, child) => ResponsiveBreakpoints.builder(
        child: child!,
        breakpoints: [
          const Breakpoint(start: 0, end: 599, name: MOBILE),
          const Breakpoint(start: 600, end: 899, name: TABLET),
          const Breakpoint(start: 900, end: double.infinity, name: DESKTOP),
        ],
      ),
    );
  }
}
